### ISSUE TITLE
Implement realm client generation

### ISSUE THREAD

**Issue by deelawn** [gnolang/gno#1319]
The goal is to write a code generation CLI tool that does the following:
- retrieve function definitions of a deployed contract
- generate a CLI tool with each supported contract function being a separate subcommand
- continue to support other `maketx` CLI flags but include reasonable default values so they must not be specified each time

**Comment by clockworkgr** [comment]
The tool should also use templating to generate a ts file of this format: 

https://github.com/gnolang/gno-js-client/blob/feat/extensible-client/src/realm-module-example/realm-module.ts 

for the various realm method calls in order to support code-completion & type-safety for realms as plugins to `gno-js client` as enabled in this PR: https://github.com/gnolang/gno-js-client/pull/57

**Comment by deelawn** [comment]
stale
