### ISSUE TITLE
Validate password by signing a blank transaction. Good idea?

### ISSUE THREAD

**Issue by jefft0** [gnolang/gno#1324]
The gnoclient package proposed in https://github.com/gnolang/gno/pull/1047 has a `Validate` method with a TODO for "Also verify if the password unlocks the account." GnoMobile has a copy of the gnoclient package. In our copy we have [implemented the password check](https://github.com/gnolang/gnomobile/commit/7a00fd1b230973c30a19fd8eb4c775dd4d939c5e) by creating a blank transaction and calling the available interface method for `Sign`. This works and is fairly compact.

Our question: Is there a preferred or better way to do a test decryption of the private key? (There are lower-level functions but those are private and specific to a particular Keybase implementation.)

```
	msg := vm.MsgCall{
		Caller: s.Info().GetAddress(),
	}
	signCfg := SignCfg{
		UnsignedTX: std.Tx{
			Msgs: []std.Msg{msg},
			Fee:  std.NewFee(0, std.NewCoin("ugnot", 1000000)),
		},
	}
	if _, err = s.Sign(signCfg); err != nil {
		return err
	}
```

**Comment by moul** [comment]
I agree this is a smart approach. What's important is not just having a valid password, but being able to use the private key's functions. When using alternatives like a ledger or multisig, the user experience (UX) won't be the same.

For command-line interfaces (CLI), a good method is to skip the initial checks and only check for errors or problems when you actually need to sign something with the private key.

For mobile apps or systems with a sign-up process, I see why you'd want this method, and I think it's a good enough solution.

However, with a ledger, you wouldn't do this check because it's not helpful and can be annoying. Instead, you should just confirm the public key, either through the ledger's API or by scanning a QR code or something similar. So, in some cases, like with a ledger, you might choose to not check at all and just wait until you really need to use the key.

**Comment by jefft0** [comment]
Thanks for the detailed response. This answers our question. Should we close this issue?
