### ISSUE TITLE
[Question] Create realm at runtime.

### ISSUE THREAD

**Issue by maxinmos** [gnolang/gno#1488]
## Description
Is it possible to create a realm at runtime in Gnolang similar to Solidity's create2?

**Comment by leohhhn** [comment]
Hey @maxinmos, thanks for the question. Currently it is not possible to do this, but is on the team's discussion list as this is quite a useful feature.

**Comment by thehowl** [comment]
I'm closing this as the question's been answered. We will likely tackle this in one way or another at one point, but we're unlikely to "forget" to do it and I'd rather have a full proposal (with a design of how this would work in code) be added to our issue tracker.

@maxinmos, since you brought it up, if you've been playing with Gno and have some ideas on how this could work, I invite you to create a proposal issue so we can kick-start a discussion :)
