### ISSUE TITLE
Error : cannot modify external-realm or non-realm object

### ISSUE THREAD

**Issue by DIGIX666** [gnolang/gno#1904]
I create a file test for my realm but I have this error `test pkg: panic: cannot modifiy external-realm or non-realm object`

<img width="1463" alt="SCR-20240408-qvih" src="https://github.com/gnolang/gno/assets/90353329/f4356c21-3fbc-4bc5-b837-f73e26b7cccf">

In my code, I think I don't call other realm for modify.
Does anyone know what the problem is?

[Link for my code](https://github.com/DIGIX666/gno/tree/theo/examples/gno.land/r/demo/library)

**Comment by deelawn** [comment]
Hey @DIGIX666.  This looks like it is expected behavior, though the error message here could be improved.  The short explanation is that modification of package (`/p/`) state is now allowed after package initialization.  So when that realm test is run, it produces an error because it tries to add a new book to the package's state.  The ideal approach for something like this is to store state in the realm by defining a type in the package that has methods to modify the state owned by the realm.  Something like:
```go
type Library struct {
    books []Book
}

func (l *Library) AddBook(id, title, author string) {
    l.books = append(l.books, Book{...})
}
```

Then in the realm:
```go
var lib libPkg.Library

func AddBook(id, title, author string) string {
	lib.AddBook(id, title, author)
	return "Book added successfully"
}
```
So try something like that and let me know if that fixes it.

**Comment by DIGIX666** [comment]
<img width="341" alt="SCR-20240409-sjmm-3" src="https://github.com/gnolang/gno/assets/90353329/772bb24b-eca8-4b2d-a9b4-3d31e3dfe7c8">
<img width="635" alt="SCR-20240409-skrv" src="https://github.com/gnolang/gno/assets/90353329/dc2b5230-2b13-457d-9924-59a5a6f7112e">

Thanks a lot for your explication ^^ 

I just changed
```go
var lib libPkg.Library
```
to
```go
var lib library.Library
```

**Comment by deelawn** [comment]
No problem -- glad you got it figured out
