### ISSUE TITLE
About gno-kedin

### ISSUE THREAD

**Issue by iam-agf** [gnolang/gno#2069]
## Description

Currently there is no path to follow for the gno-kedin project so I made this issue in order to know which is the roadmap for it in order to work on it. 

I have made a draft for what I understand about a similar to Linkedin in Gno, but since I don't know the main goal behind the project, I don't know if it's useful to start or the idea is a complete different one.

[Link to draft](https://github.com/iam-agf/gno-kedin) [If you run the start.sh file, you can see a test of how it works, but also you can follow the code, currently it's very simple to follow]

**Comment by Kouteki** [comment]
Our [hackerspace repo](https://github.com/gnolang/hackerspace) would be perfect for this. Open an issue and document your journey, e.g. something like Onbloc did [here](https://github.com/gnolang/hackerspace/issues/29).

Closing this issue 🙇

**Comment by iam-agf** [comment]
@Kouteki I get your comment, but my idea was to know which is the mental idea the team has about gno-kedIn in order to work on something useful/usable. Maybe @moul or @thehowl could have an idea?

**Comment by moul** [comment]
I'm not sure if 'LinkedIn' is the best comparison. It's more like a mix of a 'GitHub Profile' and a 'Stack Overflow Profile.' Essentially, it's a reputation-based system that showcases your contributions and expertise. By visiting your profile, one can quickly understand your areas of expertise, recent activities, recognized skills, and associations with projects or teams. It's primarily a UI to display an on-chain portfolio based on on-chain events.

The goal is to integrate it with Game of Realms, and later with WorxDAO and GovDAO, to facilitate the review of contributors and voting on roles, responsibilities, and levels. The challenge here is to blend on-chain data with manual data. Similar to LinkedIn, where you can describe yourself and add external links, a significant part of this system becomes more trustworthy because it's automated on-chain.

**Comment by iam-agf** [comment]
A Stack Overflow can be easily made with the tools that are currently existing. The issue would be to associate the content of a Github Profile since you need to have some sort of connection that keeps accountability of your PRs, commits, etc. This could be the complicated part. @moul If I do a draft for the Stack Overflow profile idea I have in the hackerspace repo @Kouteki mentioned could you consider reviewing it and tell me if worths it to continue that idea? (I emphasize in the fact that would be a purely StackOverflow profile and wouldn't related too much to Github since that would be a very heavier idea)
