### ISSUE TITLE
gnokey add can't add pubkeys

### ISSUE THREAD

**Issue by jaekwon** [gnolang/gno#241]
i think it might be failing due to a bech32 decoding error.
it could be that the prefix is set to "g" and length assumed to be shorter than a "gpub" prefixed bech32 pubkey.
i suppose we should check the prefix and then check the length accordingly, in some places.

**Comment by piux2** [comment]
Trade-Off: 

Since Bech32 is designed for max length 90 bytes/character with 6 checksum characters to detect and correct 4 errors with 0 faults. When we extend the length to 104, it will slightly decrease the success rate of error detection. 

However, the chances of failure could be tiny. According to the [BIP173]( https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki#checksum-design)  the current code selection performs well up to 1023  characters.

In addition, bech32 is used to import and store pubkeys to the local file system, we still have the true copy on-chain.

**Comment by jaekwon** [comment]
that sounds great, yes please.

**Comment by moul** [comment]
Fixed by #264
