### ISSUE TITLE
[chain] Upload and display benchmarks for the gno monorepo

### ISSUE THREAD

**Issue by zivkovicmilos** [gnolang/gno#2432]
## Description

This task concerns better utilizing the benchmarking workflows added in by @ajnavarro:
https://github.com/gnolang/gno/tree/master/.benchmarks

Currently, the workflows for the benchmarks require a dedicated machine (runner) to trigger and upload benchmark data on GH pages.

Definition of done:
- Gno monorepo benchmarks are generated and uploaded on each **master** push
- Gno monorepo benchmarks are viewable on the adequate GH page, which include historical data

**Comment by sw360cab** [comment]
Where are benchmarks results supposed to be published at?

Was this URL working:https://gnolang.github.io/benchmarks/
and it stopped at some point or it never worked?

**Comment by zivkovicmilos** [comment]
I think it's working now, just showing 404 because there is no benchmark data

**Comment by zivkovicmilos** [comment]
We can host it anywhere you think it makes sense

**Comment by sw360cab** [comment]
Nice.
I understand and reconstructed the process also looking into that.

https://github.com/bobheadxi/gobenchdata/issues/76
https://github.com/gnolang/gno/pull/881

But I have seen that benchmark related workflows are actually disabled / or not working.
Basically again because of this: https://github.com/bobheadxi/gobenchdata/issues/76

**Comment by sw360cab** [comment]
I have no hint where the dedicated Runner is at, I expected everything running in Github, but maybe these tasks are too heavy to run within Github's runners.

**Comment by sw360cab** [comment]
References:

#2716
#2861
#2891
#2895
#2966
