### ISSUE TITLE
Faucet not working / broken

### ISSUE THREAD

**Issue by itinance** [gnolang/gno#458]
Hi.

Using the faucet under  `https://test3.gno.land/r/gnoland/faucet` (according to "Getting Started") seems to be broken. 
It only shows

> Post "http://gnoland:36657": EOF

**Comment by zivkovicmilos** [comment]
Hey @itinance,

I believe we've closed off the testnet faucet a while back. Do you need `testnet3` funds exclusively, or just something local to play around with?

If it's local funds you're after, you can spin up a faucet for your local chain by following the [README guide](https://github.com/gnolang/gno/tree/master/cmd/gnofaucet) we have for the `gnofaucet` command.

Otherwise if it's for the testnet, can you please leave your address? I'm sure we can transfer some `testnet3` GNOT for you to use.

**Comment by itinance** [comment]
Thanks a lot, @zivkovicmilos 

at the moment I would be fine with local funds and will spin up a local chain.
However, if my local work will be successful, I would rather test on testnet also 😅

So if it's not an inconvenience, I would be glad to receive some testnet3 GNOTs at g1ju6tdtqenzm5j38h8s2546xngqh9x43eymjjmt 

Many thanks ♥️♥️♥️

**Comment by zivkovicmilos** [comment]
Hey @itinance,

I've just noticed that our staging environment was down - it's back online now. You can use the staging environment instead of the `testnet3` to play around with a live instance of the network, it's located [here](https://staging.gno.land).

The faucet for the staging environment (confirmed to work) can be found [here](https://staging.gno.land/faucet). Please note that the staging environment is wiped with every commit to master, I believe.

I'll write up a short guide to help other users who might also be wondering how to acquire network currency. In the meantime, I'm closing this issue.

Please let me know if you need any further info, and don't hesitate to open an issue / discussion if you come across something that needs another set of eyes 🙏

**Comment by itinance** [comment]
Thanks @zivkovicmilos 

confirmed, the faucet at https://staging.gno.land/faucet works perfectly! 

Maybe it's worth to mention that all links on the [staging index page](https://staging.gno.land/) are pointing to test3, where the faucet not works. I think this leads to issues like mine :)

**Comment by zivkovicmilos** [comment]
Hey @itinance,

Noticed that as well when I was checking it out. I've opened up a PR to resolve this, so it shouldn't be an issue in the future.

Thank you for raising the concern 🙏
