### ISSUE TITLE
Contract call on Gnolang

### ISSUE THREAD

**Issue by go7066** [gnolang/gno#490]
I am a Teritori team member and we have built multisig (project name called gnosig) in Gnolang as part of our contribution to Gnoland ecosystem - voting and proposals posting part are done.
The problem is the contract call part where multisig should execute once it's approved.
Is there any interface to call a contract something like this on the contract side?
```
Contract(contractAddress).Function(Params...)
```

There's no documentation written about this anywhere.

**Comment by moul** [comment]
Hey @go7066, I moved the issue on the main repo.

**Comment by go7066** [comment]
@moul couldn't find any contract call within a contract on examples folder.

**Comment by go7066** [comment]
> Hey @go7066, I moved the issue on the main repo.
Can you confirm which issue ticket is created by closing this issue? (Which one is the main repo for the issue ticket?

**Comment by tbruyelle** [comment]
![image](https://github.com/gnolang/gno/assets/92280/a755ebf6-bcff-4c84-8d34-563179e90d30)

 @go7066 the reason why you can't call `boards.CreateBoard()` from an other contract is because the function requires to be called directly by the user.  This is because at the beginning of the function `std.AssertOriginCall()` is invoked. `std.AssertOriginCall` panics if the caller is an other contract.

So it is by design, you can't do anything about it. 

Other functions that doesn't invoke `std.AssertOriginCall()` can be called from other contracts without issue.
