### ISSUE TITLE
change default directory for `$GNO_HOME` on gnokey

### ISSUE THREAD

**Issue by thehowl** [gnolang/gno#655]
#141 introduced `~/.gno` as the default "home directory" used in gnokey. I see the PR has introduced it without much discussion, so I'd like to bring it up here (and eventually change that).

My personal preference is that I generally have a strong distaste for software that creates more directories in my home dir. On top of this, this is generally not equivalent across platforms (ie., while creating ~/.gno will succeed on Windows, it will not be a hidden directory).

My proposal is to use [`os.UserConfigDir()`](https://pkg.go.dev/os#UserConfigDir) joined with "gno".
The default behaviour should still be backwards compatible, so if `~/.gno` is an existing directory, then that should be used by default instead. And of course, `$GNO_HOME` is honoured as an environment var is set.

(From discussion on #652)

**Comment by moul** [comment]
Sounds good to me. Anyone with another proposal?

Note that at this stage we don't need to ensure backward compatibility for such things.

**Comment by moul** [comment]
After researching other projects with similar concerns, I believe that `os.UserConfigDir` is the ideal and comprehensive solution.

Since we are only supporting recent versions of Golang, we do not need to worry about running code with versions prior to Go 1.12.

For motivation in the right direction, check out this example: https://github.com/moby/moby/issues/40848.

**Comment by thehowl** [comment]
#719
