### ISSUE TITLE
[RFC] Handling nested packages 

### ISSUE THREAD

**Issue by harry-hov** [gnolang/gno#852]
## Description

Currently, when we publish a package on the chain, the process overlooks the subdirectories within that package. As a result, when we publish a package, such as "example/a," it does not automatically publish its nested package "example/a/b.". Users are required to publish the nested package separately, leading to potential inconveniences and confusion.

## Expected behavior and potential solution

It would be highly beneficial if the publication process for packages on the chain included the automatic publication of nested packages. By recognizing and publishing subdirectories within a package, such as "example/a/b" when "example/a" is published, users would be spared the need for separate publishing actions, thereby simplifying the package management workflow.

Maybe we can also leverage `gno.mod` file to to identify the root directory of the package. And can utilize this information while publishing nested packages within the root directory when publishing the parent package.

## Steps to Reproduce:

1. Create a realm/package with nested subdirectories, e.g `/examples/gno.land/p/demo/foo/bar` 
2. Publish the parent package (i.e `/examples/gno.land/p/demo/foo`) on the chain.
    
    ```
    gnokey maketx addpkg -pkgpath "gno.land/p/demo/foo" -pkgdir "/examples/gno.land/p/demo/foo" 
    -deposit 10000000ugnot -gas-fee 1000000ugnot -gas-wanted 2000000 -broadcast testkey
    ```
4. Observe that the nested package (`gno.land/p/demo/foo/bar`) is not automatically published alongside its parent.

## Additional Information

In Go, nested packages are handled through the `go.mod` file, which serves as the module definition and dependency management tool. The go.mod file resides at the root of a module and determines the structure of package.

The go.mod file includes the module name, and the nested packages derive their names based on their relative paths from the root directory of the module.

Maybe we can do something like that?

**Comment by moul** [comment]
We have several goals to achieve:

1. Enable the upload of subdirectories along with the top-level package/realm through the CLI.
2. Ensure that the web interface fully supports subfolders, including the help page, source page, and other relevant sections.
3. Implement safeguards to prevent uploading a package/realm under an existing one, until we resolve potential conflicts and establish a user-friendly way to navigate and explore sub-entities via the web interface.
4. Ideally, allow the splitting of exposed functions from a realm into subfolders, enabling calls like `gno.land/r/demo/blog/admin.DoStuff` instead of being limited to `gno.land/r/demo/blog.AdminDoStuff`. The top-level folder of a realm should serve as the discovery URL for most users, while subfolders can cater to specialized audiences such as administrators, moderators, debugging, or facilitating the segmentation of a large application into smaller components.
