### ISSUE TITLE
Send via username (gnot, grc20)

### ISSUE THREAD

**Issue by 2woongjae** [gnolang/gno#878]
## Description

Hi. I'm developing Adena Wallet.

I tried sending via the **username** registered in `r/demo/users` package instead of the **address**, but it didn't work.

Is this intended or is it a missing feature?

If that is the intent, we are concerned about adding the feature to send by username.
If it's a missing feature, I can open a PR.

Thank you for your interest in my question.

**Comment by moul** [comment]
The content in the `r/demo/*` repository is currently unofficial. The `GRC20` implementation is designed to be independent of r/demo/users to maintain simplicity. However, through composition, a GRC20WithUsersSupport could be created and potentially become widely used.

The `r/demo/foo20` instance of `GRC20` utilizes `users.AddressOrName`, providing what you expect (see https://github.com/gnolang/gno/blob/master/examples/gno.land/r/demo/foo20/foo20.gno#L50).

The `$GNOT` (native token) is not aware of `r/demo/users` and is unlikely to integrate with it.

You can expect than more contracts adopt `users.AddressOrName` instead of `std.Address`. However, it may make sense for wallets to automatically resolve `r/demo/users` with caching, similar to how a browser manages DNS. This would involve parsing the contract addresses and dynamically calling `r/demo/users` for resolution.

**Comment by 2woongjae** [comment]
@moul Thanks for the answer!

I checked and it is still possible to send `GRC20` via username as you said.

But it's unofficial, and I know you guys are working on a new `GRC20` spec, so we're not going to add the feature right away, but will think about it carefully.

I also understand that The `$GNOT` (native token) is not aware of r/demo/users and is unlikely to integrate with it.

I'll keep an eye on the project and try it when the time comes.
