### ISSUE TITLE
Providing ast tools like Go

### ISSUE THREAD

**Issue by peter7891** [gnolang/gno#946]
This is necessary for simple AST processing, including the GC and many other things we might do in the future.
https://go.dev/src/go/ast/walk.go

**Comment by mvertes** [comment]
We need a tree walk function which is able to perform both node pre-processing and post-processing. Pre-processing is done at node entry, post-processing at node exit, when all the sub-trees have also been processed.

A lot of important compiler/interpreter tasks like type analysis, memory analysis (including escape analysis), control-flow graph analysis, and in future, byte code generation, various optimisations, etc, even code evaluation could be done in a much simpler and more efficient way using node post-processing callbacks.

Unfortunately, this is not provided by the standard library Go AST, which only provides pre-processing.

I propose that we first add a tree walk function supporting node post-processing callbacks to the GNO AST package, and then that we implement, or re-implement, on demand, the various tasks which could benefit from that.

This could be added without disturbing the existing code.

**Comment by thehowl** [comment]
> I propose that we first add a tree walk function supporting node post-processing callbacks to the GNO AST package, and then that we implement, or re-implement, on demand, the various tasks which could benefit from that.

In a nutshell: are we talking about making a gno fork of `go/{ast,parser}`?

**Comment by peter7891** [comment]
> > I propose that we first add a tree walk function supporting node post-processing callbacks to the GNO AST package, and then that we implement, or re-implement, on demand, the various tasks which could benefit from that.
> 
> In a nutshell: are we talking about making a gno fork of `go/{ast,parser}`?

No. We need to provide functionality to manipulate the Gno AST easily.

**Comment by jaekwon** [comment]
> We need a tree walk function which is able to perform both node pre-processing and post-processing. Pre-processing is done at node entry, post-processing at node exit, when all the sub-trees have also been processed.

The transcribe.go file already includes hooks for both node entry and node exit.
In the preprocess.go, both TRANS_ENTER and TRANS_LEAVE cases are used.
Because of the way that transcribe is implemented, and also with TRANS_BLOCK and TRANS_BLOCK2 for cases where additional hooks are necessary (we could add more if really necessary), the preprocessor is able to do things in depth-search-first manner and interweave TRANS_ENTERs and TRANS_LEAVEs.

The function is called "preprocess" because it's done before executing, and I figured "process" is ambiguous and confusing.

We can always implement additional functions that call transcribe, like preprocess1, preprocess2, and so on, and each of these could also only have ENTERs or LEAVEs if that makes sense. But I'm not sure why that would be, for a language like go/gno whose AST has sufficient "locality" and "tree-ness". For example, all the preprocessing of the RHS of a statement is completed before even needing to look at the LHS, which only needs to happen strictly after the RHS. 

```
> STMT is LHS := RHS
ENTER STMT
ENTER RHS
... more RHS stuff
LEAVE RHS
ENTER LHS
... more LHS stuff
LEAVE LHS
LEAVE STMT
```

> A lot of important compiler/interpreter tasks like type analysis, memory analysis (including escape analysis), control-flow graph analysis, and in future, byte code generation, various optimisations, etc, even code evaluation could be done in a much simpler and more efficient way using node post-processing callbacks.

FYI static type evaluation is also done in the preprocessor, all with one depth-first-search swoop.
I would put escape analysis under the category of optimizations. The intent is to keep optimizations out of the implementation of the gno vm so that it can serve as a minimal intuitive spec forever. Forks can then do various optimizations that try to preserve the behavior of the spec. If any optimization can be done intuitively and simply, then we can consider adding it to the gno vm, but I don't think optimizations from escape analysis belong there.

In any case, these various tasks can each be their own function (preprocess_typeanalysis, preprocess_escapeanalysis, postprocess_generatebytecode, preprocess_optimization1 etc) that do depth-first walks, interweaving ENTERs and LEAVEs if necessary. In the end we'd have a sequence of preprocessing. Here call it POSTprocess_generatebytecode only because there is no interpretation of the AST.

After launch we can try to break up the existing Preprocess() function into multiple stages, if the end result is intuitive and simpler than what we already have.
